blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0, 'Draft'),
    (1, 'Publish'),
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']
    
    def __str__(self) -> str:
        return self.title

blog/views.py
from django.views import generic
from .models import Post


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'blog/css/index.css' %}">

{% include 'blog/partials/_header.html' %}

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %} {% include 'blog/partials/_card.html' %} {% endfor %}
        </div>

        <!-- Sidebar -->
        {% include 'blog/partials/_sidebar.html' %}
    </div>
</div>

{% endblock content %}

blog/templates/blog/partials/_card.html
<div class="card mb-4">
    <div class="card-body">
        <h2 class="card-title">{{ post.title }}</h2>
        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
        <p class="card-text">{{post.content|slice:":200" }}</p>
        <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
    </div>
</div>

blog/templates/blog/partials/_header.html
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class="site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog</h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp</p>
                </div>
            </div>
        </div>
    </div>
</header>

blog/templates/blog/partials/_sidebar.html
{% block sidebar %}

<style>
    .card{
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
            <a href="https://djangocentral.com/building-a-blog-application-with-django"
            class="btn btn-danger">Know more!</a>
        </div>
    </div>
</div>

{% endblock sidebar %}

templates/base.html
{% load static %}

<html>
{% include 'partials/_head.html' %}

<body>
    <link rel="stylesheet" href="{% static 'global/css/base.css' %}">

    <!-- Navigation bar -->
    {% include 'partials/_nav.html' %}

    {% block content %}
    <!-- Content goes here -->
    {% endblock content %}

    <!-- Footer -->
    {% include 'partials/_footer.html' %}
</body>

</html>

templates/partials/_footer.html
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
</footer>

templates/partials/_head.html
<head>
    <title>My Site | Blog</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    <meta name="google" content="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Django central</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">About</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>